### ISSUE TITLE
Support for `none`

### ISSUE THREAD

**Issue by svgeesus** [color-js/color.js#228]
We currently don't accept the keyword [`none`](http://w3c.github.io/csswg-drafts/css-color-4/#missing), nor do we generate it on serialization.

**Comment by svgeesus** [comment]
Even when we generate a color with `NaN` as the hue, we still serialize it as `0`: `rgba(0 0 0 / 0)` converts to Oklch with the coordinates `[0, 0, NaN]` and we serialize as  [`oklch(0 0 0 / 0)`](https://colorjs.io/apps/convert/?color=oklch(0%200%200%20%2F%200)&precision=10)

**Comment by svgeesus** [comment]
Culprit is in [serialize.js](https://github.com/LeaVerou/color.js/blob/2bd19b0a913da3f3310b9d8c1daa859ceb123c37/src/serialize.js#L35-L38)

```js
	// Convert NaN to zeros to have a chance at a valid CSS color
	// Also convert -0 to 0
	// This also clones it so we can manipulate it
	coords = coords.map(c => c? c : 0);
```

**Comment by LeaVerou** [comment]
So there are two components to this:

- [ ] Support parsing `none` (convert it to `NaN`)
- [ ] Support outputting `none`

The last bit is tricky: we want `serialize()` to output `none`, but `display()` should not unless the browser actually supports it. So, the only way I see to do this, is to add an option to `serialize()` which converts `NaN` to `0` (the current default, which should now be the not-default — I think the compat risk here is minimal). Then, if the color has `NaN` components, `display()` can check if `none` is supported, and use the appropriate option.

**Comment by LeaVerou** [comment]
Done, we can probably close this now.
In the end `display()` does its own stripping of `none` so we ended up not needing the option in `serialize()` so I removed it.

**Comment by svgeesus** [comment]
@LeaVerou our [color parsing tests](https://colorjs.io/tests/parse) are still failing because they expect to find `NaN` in `coords` but find `null` instead.

**Comment by LeaVerou** [comment]
> @LeaVerou our [color parsing tests](https://colorjs.io/tests/parse) are still failing because they expect to find `NaN` in `coords` but find `null` instead.

They're all passing, so closing this again
